### ISSUE TITLE
Sequelize migration error

### ISSUE THREAD

**Issue by vyatsun** [kwhinnery/todomvc-plusplus#51]
I'm having the following error when trying to run 
`sequelize db:migrate`

```
Sequelize [Node: 8.4.0, CLI: 2.8.0, ORM: 1.7.5]

Loaded configuration file "db/database.js".
Using environment "development".
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:102:11)
    at Object.urlParse [as parse] (url.js:96:5)
    at new Sequelize (/mnt/shared/lib/node_modules/sequelize/lib/sequelize.js:59:22)
    at getSequelizeInstance (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:394:12)
    at getMigrator (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:403:21)
    at Object.task (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:23:14)
    at /home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at Url.parse (url.js:102:11)
    at Object.urlParse [as parse] (url.js:96:5)
    at new Sequelize (/mnt/shared/lib/node_modules/sequelize/lib/sequelize.js:59:22)
    at getSequelizeInstance (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:394:12)
    at getMigrator (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:403:21)
    at Object.task (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:23:14)
    at /home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
```

**Comment by Maks-Yaremenko** [comment]
+1
